// Copyright (c) 2026 Lior Ben-Gai
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Regenerates src/fonts/pixel-operator.js: the Pixel Operator TTFs inlined as
// base64 so the library (and the single-file build) carries its default print
// font with no network or file-path dependency. Run: npm run embed-fonts

import { readFile, writeFile } from 'node:fs/promises';

const dir = new URL('../src/fonts/Pixel Operator Font/', import.meta.url);
const FACES = [
  ['Pixel Operator', 'PixelOperator8.ttf'],
  ['Pixel Operator Mono', 'PixelOperatorMono8.ttf'],
];

const entries = [];
for (const [family, file] of FACES) {
  const b64 = (await readFile(new URL(file, dir))).toString('base64');
  entries.push(`  ${JSON.stringify(family)}: { grid: 8, data: ${JSON.stringify(b64)} },`);
}

await writeFile(new URL('../src/fonts/pixel-operator.js', import.meta.url), `// Copyright (c) 2026 Lior Ben-Gai\n// This Source Code Form is subject to the terms of the Mozilla Public\n// License, v. 2.0. If a copy of the MPL was not distributed with this\n// file, You can obtain one at https://mozilla.org/MPL/2.0/.\n\n// GENERATED by scripts/embed-fonts.mjs — do not edit by hand.
//
// Pixel Operator by Jayvee Enaguas, CC0 1.0 Universal (public domain).
// The 8px-grid TTFs, base64-encoded.

export const PIXEL_OPERATOR = {
${entries.join('\n')}
};
`);
console.log(`embedded ${FACES.length} faces`);
