// Copyright (c) 2026 Lior Ben-Gai
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Safe reader for the small JavaScript subset emitted by Document.toCode().
// This deliberately does not use eval/Function: pasted template code is data,
// never executable code.

export const TEMPLATE_IMAGE_SOURCE = Symbol('hotspring template image source');

const METHODS = new Set(['text', 'image', 'qr', 'table', 'hr', 'spacer', 'cut', 'calibration']);
const COMMON_OPTIONS = ['space', 'spaceBefore', 'spaceAfter', 'cutFeed'];
const OPTION_KEYS = {
  text: [...COMMON_OPTIONS, 'font', 'size', 'align', 'bold', 'pad'],
  image: [...COMMON_OPTIONS, 'scale', 'height', 'offsetX', 'offsetY', 'algo', 'threshold', 'brightness', 'contrast', 'gamma', 'sharpen'],
  qr: [...COMMON_OPTIONS, 'ecl', 'moduleSize', 'quiet', 'align'],
  table: [...COMMON_OPTIONS, 'font', 'size', 'header', 'widths', 'align', 'border', 'padding'],
  hr: [...COMMON_OPTIONS, 'thickness', 'dashOn', 'dashOff', 'inset'],
};

function isObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

class Reader {
  constructor(source, index = 0) {
    this.source = source;
    this.index = index;
  }

  error(message) {
    const line = this.source.slice(0, this.index).split('\n').length;
    throw new SyntaxError(`${message} (line ${line})`);
  }

  skip() {
    while (/\s/.test(this.source[this.index] || '')) this.index++;
  }

  take(token) {
    this.skip();
    if (!this.source.startsWith(token, this.index)) return false;
    this.index += token.length;
    return true;
  }

  expect(token) {
    if (!this.take(token)) this.error(`Expected ${JSON.stringify(token)}`);
  }

  identifier() {
    this.skip();
    const match = /^[A-Za-z_$][A-Za-z0-9_$]*/.exec(this.source.slice(this.index));
    if (!match) this.error('Expected an identifier');
    this.index += match[0].length;
    return match[0];
  }

  string() {
    this.skip();
    if (this.source[this.index] !== '"') {
      this.error('Expected a double-quoted string as generated by Copy code');
    }
    const start = this.index++;
    let escaped = false;
    while (this.index < this.source.length) {
      const char = this.source[this.index++];
      if (escaped) escaped = false;
      else if (char === '\\') escaped = true;
      else if (char === '"') {
        let value;
        try { value = JSON.parse(this.source.slice(start, this.index)); }
        catch { this.error('Invalid string literal'); }
        if (value.length > 16 * 1024) this.error('A template string may not exceed 16 KiB');
        return value;
      }
    }
    this.error('Unterminated string literal');
  }

  number() {
    this.skip();
    const match = /^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/.exec(this.source.slice(this.index));
    if (!match) this.error('Expected a number');
    this.index += match[0].length;
    const value = Number(match[0]);
    if (!Number.isFinite(value)) this.error('Number must be finite');
    return value;
  }

  value(depth = 0) {
    if (depth > 10) this.error('Template values are nested too deeply');
    this.skip();
    const char = this.source[this.index];
    if (char === '"') return this.string();
    if (char === '{') return this.object(depth + 1);
    if (char === '[') return this.array(depth + 1);
    if (char === '-' || /\d/.test(char || '')) return this.number();

    const word = this.identifier();
    if (word === 'true') return true;
    if (word === 'false') return false;
    if (word === 'null') return null;
    if (word === 'source') return TEMPLATE_IMAGE_SOURCE;
    this.error(`Unsupported value ${JSON.stringify(word)}`);
  }

  object(depth) {
    const value = Object.create(null);
    this.expect('{');
    if (this.take('}')) return value;
    while (true) {
      this.skip();
      const key = this.source[this.index] === '"' ? this.string() : this.identifier();
      if (Object.hasOwn(value, key)) this.error(`Duplicate option ${JSON.stringify(key)}`);
      this.expect(':');
      value[key] = this.value(depth);
      if (this.take('}')) return value;
      this.expect(',');
    }
  }

  array(depth) {
    const value = [];
    this.expect('[');
    if (this.take(']')) return value;
    while (true) {
      value.push(this.value(depth));
      if (this.take(']')) return value;
      this.expect(',');
    }
  }

  arguments() {
    const args = [];
    this.expect('(');
    if (this.take(')')) return args;
    while (true) {
      args.push(this.value());
      if (this.take(')')) return args;
      this.expect(',');
    }
  }
}

function checkOptions(method, options) {
  if (!isObject(options)) throw new TypeError(`${method} options must be an object`);
  const allowed = new Set(OPTION_KEYS[method] || []);
  for (const key of Object.keys(options)) {
    if (!allowed.has(key)) throw new TypeError(`${method} option ${JSON.stringify(key)} is not supported by the demo`);
  }
}

function checkComponent({ method, args }) {
  const options = args[1];
  if (['text', 'qr', 'table'].includes(method)) {
    if (args.length < 1 || args.length > 2 || typeof args[0] !== 'string') {
      throw new TypeError(`${method} expects a string and optional options`);
    }
    if (options !== undefined) checkOptions(method, options);
    return;
  }
  if (method === 'image') {
    if (args.length < 1 || args.length > 2 || args[0] !== TEMPLATE_IMAGE_SOURCE) {
      throw new TypeError('image expects the generated source placeholder and optional options');
    }
    if (options !== undefined) checkOptions(method, options);
    return;
  }
  if (method === 'hr') {
    if (args.length > 1) throw new TypeError('hr expects optional options only');
    if (args[0] !== undefined) checkOptions(method, args[0]);
    return;
  }
  if (method === 'spacer') {
    if (args.length !== 1 || typeof args[0] !== 'number') throw new TypeError('spacer expects one numeric height');
    return;
  }
  if (args.length) throw new TypeError(`${method} does not accept arguments in generated templates`);
}

/** Parse the exact, literal-only chain format produced by Document.toCode(). */
export function parseTemplateCode(source) {
  if (typeof source !== 'string') throw new TypeError('Template code must be a string');
  if (!source.trim()) throw new SyntaxError('Paste template code copied from Hotspring');
  if (source.length > 256 * 1024) throw new RangeError('Template code is too large');

  const assignment = /\bconst\s+doc\s*=\s*new\s+Document\s*\(/g.exec(source);
  if (!assignment) throw new SyntaxError('Could not find "const doc = new Document(...)"');

  const reader = new Reader(source, assignment.index + assignment[0].length);
  const options = reader.value();
  if (!isObject(options)) throw new TypeError('Document options must be an object');
  for (const key of Object.keys(options)) {
    if (!['width', 'spacing', 'cutFeed'].includes(key)) {
      throw new TypeError(`Document option ${JSON.stringify(key)} is not supported by the demo`);
    }
  }
  reader.expect(')');
  reader.expect(';');

  const chain = /\bdoc\s*(?=\.|;)/g;
  chain.lastIndex = reader.index;
  const start = chain.exec(source);
  if (!start) throw new SyntaxError('Could not find the document component chain');
  reader.index = start.index;
  if (reader.identifier() !== 'doc') reader.error('Expected the doc chain');

  const components = [];
  while (reader.take('.')) {
    const method = reader.identifier();
    if (!METHODS.has(method)) reader.error(`Unsupported document method ${JSON.stringify(method)}`);
    const component = { method, args: reader.arguments() };
    checkComponent(component);
    components.push(component);
    if (components.length > 200) throw new RangeError('A template may contain at most 200 components');
  }
  reader.expect(';');
  return { options, components };
}
